services:

  profile-db:
    image: postgres:17-alpine
    container_name: postgres_profile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: profile
    volumes:
      - postgres_profile_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./infrastructure/vault-config/secrets:/vault/config/secrets
      - ./infrastructure/vault-entrypoint.sh:/vault-entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: [ "/bin/sh", "/vault-entrypoint.sh" ]

volumes:
  postgres_profile_data:
  vault_data: