services:

  profile-db:
    image: postgres:17-alpine
    container_name: postgres_profile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: profile
    volumes:
      - postgres_profile_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak-db:
    image: postgres:17-alpine
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./infrastructure/vault-config/secrets:/vault/config/secrets
      - ./infrastructure/vault-entrypoint.sh:/vault-entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: [ "/bin/sh", "/vault-entrypoint.sh" ]

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_CLIENT_SECRET: m#5Fhj2$8xLp9!qB6*KvE@W7nGd4%zR1
      KC_IMPORT_PATH: /opt/keycloak/data/import/
      KC_IMPORT_FORCE: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_LOG_LEVEL: DEBUG
    volumes:
      - ./infrastructure/keycloak-config/:/opt/keycloak/data/import/
    command:
      - start-dev
      - --import-realm
    ports:
      - "8095:8080"
    depends_on:
      - keycloak-db

volumes:
  postgres_profile_data:
  postgres_keycloak_data:
  vault_data: