server:
  port: 8082

spring:
  application:
    name: api-gateway

keycloak:
  realm: my-realm
  auth-server-url: http://localhost:8095

services:
  user-service-url: http://localhost:8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
    instances:
      keycloakService:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      keycloakService:
        baseConfig: default

logging:
  level:
    com.cor.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
