server:
  port: 8081

spring:
  application:
   name: user-service

  config:
    import: vault://

  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        application-name: user-service

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: false



  datasource:
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

keycloak:
  realm: my-realm
  auth-server-url: http://localhost:8095
  client-id: authservice-client
  client-secret: m#5Fhj2$8xLp9!qB6*KvE@W7nGd4%zR1
  admin:
    username: admin
    password: admin
    client-id: admin-cli
    realm: master

resilience4j:
  circuitbreaker:
    instances:
      keycloakService:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

logging:
  level:
    liquibase: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.vault: DEBUG
    root: debug
